# DEBUG BUILD: display only
CONFIG_GPIO=y
CONFIG_SPI=y

# Console via RTT
CONFIG_SERIAL=n
CONFIG_CONSOLE=y
CONFIG_RTT_CONSOLE=y
CONFIG_USE_SEGGER_RTT=y

# Logging
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# Display subsystem + Zephyr built-in SSD1306/SSD1309 driver
CONFIG_DISPLAY=y
CONFIG_SSD1306=y
